const questions=[
 {text:'你和队友准备进攻包点，前方明显有敌人架枪，你会：',opts:['主动走在前面，为队友创造机会','和队友并排推进，互相照应','让队友先拉枪，自己在后面等机会','直接对队友说：“你给我拉，我给你补。”然后站在墙后面观察'],dims:[5,0,0,0,0,5]},
 {text:'队友按照你的要求冲出去拉枪，已经和敌人交火，你会：',opts:['立即跟上并完成补枪','稍微等一下再跟进','等队友快死了才慢慢探头','队友已经倒地了，你还在原地调整准星，最后说“没补上”'],dims:[5,0,0,0,0,5]},
 {text:'你们一起进入包点，队友在前面吸引了全部火力，你发现自己可以从侧面支援，你会：',opts:['马上开枪帮助队友','先报点，再寻找射击角度','躲在箱子后面等待队友打残敌人','队友被集火时直接后退，把包点和队友一起留给敌人'],dims:[0,2,1,0,0,5]},
 {text:'队友被你安排去拉枪，结果你没有及时补上，导致他被击杀，你会：',opts:['承认自己判断失误','说“刚才节奏没对上”','说“我本来已经准备好了，是敌人突然露头”','理直气壮地说：“你就说我补没补吧。”'],dims:[5,5,5,0,0,2]},
 {text:'你在包点卖掉队友，队友被击杀后质问你为什么不帮忙，你会：',opts:['道歉并承认自己卖了','解释当时确实不敢出去','先问“你死没死吧”，再考虑要不要救','理直气壮地说：“你死没死吧？没死就继续打，死了说明战术成功吸引了火力。”'],dims:[3,5,5,0,0,5]},
 {text:'你借了室友的耳机，几天后发现耳机找不到了，你会：',opts:['第一时间告诉室友并道歉','先认真找一遍，确认找不到后说明情况','悄悄买一个便宜耳机，假装什么都没发生','等室友主动问起，再淡定回答：“不是不见了，是暂时消失了。”'],dims:[0,5,2,3,2,0]},
 {text:'室友继续追问：“所以我的耳机到底去哪了？”你会：',opts:['“我弄丢了，我赔你。”','“我还在找，找到马上告诉你。”','“不是找不到，是目前还没有找到。”','“它没有消失，只是暂时脱离了我们的空间。”'],dims:[0,4,5,2,1,0]},
 {text:'你承诺每天分期赔偿室友，实际只发了一天，之后被问起时你会：',opts:['继续按计划赔偿','一次性补齐大部分','解释最近比较忙，然后继续拖延','表示：“我已经赔过一天了，说明态度是有的。”'],dims:[0,4,2,2,5,0]},
 {text:'室友正在认真学英语，你突然想找他玩或制造节目效果，你会：',opts:['等他学完再找他','先问他现在是否方便','在旁边小声打扰几句，发现他认真后就离开','直接闯入学习现场，用各种动作和问题打断他，然后说：“学习这么认真干什么，先陪我玩一会儿。”'],image:'assets/q9.jpg',dims:[0,0,0,5,0,0]},
 {text:'你和队友在一起守包，炸弹要炸了，但敌人可能来拆包，你会：',opts:['和队友一起架枪，确保敌人无法拆包','主动观察关键位置，及时报点','让队友先顶住，自己在附近找安全角度','让固排留下架枪，自己先跑路，并表示：“这波我去保枪，胜利交给你们。”'],dims:[2,3,2,0,0,5]}
];
const dims=['补枪拖延度','责任逃避度','诡辩创造力','室友安宁破坏度','承诺拖欠度','队友背刺度'];
const words=[['及时补枪','偶尔慢半拍','补枪看缘分','拉枪甩锅大师'],['勇于认错','解释一下','甩锅预备役','责任蒸发术'],['直球认错','普通解释','话术绕弯','量子狡辩家'],['室友友好','轻度打扰','节目预告员','宿舍灾难导演'],['按时兑现','偶尔延期','一日承诺选手','分期付款文学家'],['团队可靠','偶尔保命','战术性撤退','惊天大卖']];
const results=[
 {title:'宿舍文明观察员',img:'assets/result1.png',summary:'你和刚哥之间还隔着一段文明距离。你的队友暂时安全，耳机也有机会平安回家。'},
 {title:'刚味试探员',img:'assets/result2.png',summary:'你偶尔会把事情处理得有点可疑，但目前还愿意回头解释，属于刚味刚刚冒头。'},
 {title:'标准刚哥：嘴硬但还能沟通',img:'assets/result3.png',summary:'你已经掌握了刚哥的基础语法：先解释，再合理化，最后用一个自信的表情结束对话。'},
 {title:'战略性卖队友艺术家',img:'assets/result4.png',summary:'你擅长把撤退讲成战术，把补不上讲成节奏问题。队友还活着，但不一定想和你排下一把。'},
 {title:'刚杂预备役',img:'assets/result5.png',summary:'你的耳机事件、承诺执行和室友节目效果已经形成稳定体系，只差一个更响亮的解释。'},
 {title:'致命刚杂：这刚杂味对了',img:'assets/result6.png',summary:'你不是在制造节目效果，你本身就是节目效果。建议队友先买保险，室友先给耳机贴定位器。'}
];
const quotes=['你死没死吧。','你给我拉，我给你补。','你就说我补没补吧。','不是不见了，是消失了。','这刚杂味对了。'];
const comments=[['你已经把补枪这件事，做成了一门等待艺术。','你的补枪不是不到，只是总在队友倒下之后抵达。'],['你对责任的态度很有弹性，能解释就绝不承认。','事情可以是你的，但责任最好先放在门外。'],['你拥有把离谱现场包装成战术复盘的稀有天赋。','只要语气够认真，任何撤退都能被讲成战略转移。'],['你的室友很难拥有一段完整且安静的学习时间。','你不一定每天整活，但每次整活都很有记忆点。'],['你的承诺开局气势十足，后续更新需要另行通知。','你不是不兑现，只是兑现周期比较有艺术感。'],['你对队友的保护方式很特别：先让他吸引火力，再保护自己的枪。','你不是卖队友，你只是把队友安排到了战术最前线。']];
let current=0,answers=Array(questions.length).fill(null),chartValues=[];
const $=id=>document.getElementById(id);const show=id=>document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('hidden',s.id!==id));
function renderQuestion(){const q=questions[current];$('questionIndex').textContent=String(current+1).padStart(2,'0');$('progressText').textContent=`${String(current+1).padStart(2,'0')} / 10`;$('progressBar').style.width=`${(current+1)*10}%`;$('questionText').textContent=q.text;$('questionImage').classList.toggle('hidden',!q.image);if(q.image)$('questionImage').src=q.image;const box=$('options');box.innerHTML='';q.opts.forEach((opt,i)=>{const b=document.createElement('button');b.className='option'+(answers[current]===i?' selected':'');b.innerHTML=`<span class="letter">${'ABCD'[i]}</span><span>${opt}</span>`;b.onclick=()=>{answers[current]=i;renderQuestion()};box.appendChild(b)});$('backBtn').disabled=current===0;$('nextBtn').disabled=answers[current]===null;$('nextBtn').textContent=current===9?'查看结果 →':'下一题 →'}
function start(){current=0;answers.fill(null);show('questionScreen');renderQuestion()}
function score(){const out=[0,0,0,0,0,0],max=[0,0,0,0,0,0];questions.forEach((q,qi)=>{const a=answers[qi]??0;const val=[0,25,75,100][a];q.dims.forEach((d,i)=>{const weight=d/5;out[i]+=val*weight;max[i]+=100*weight})});return out.map((v,i)=>max[i]?Math.round((v/max[i])*100):0)}
function wordFor(i,v){return words[i][v<40?0:v<60?1:v<80?2:3]}
function result(){chartValues=score();const total=Math.round(chartValues.reduce((a,b)=>a+b,0)/6);const idx=total<15?0:total<30?1:total<50?2:total<70?3:total<85?4:5;const r=results[idx];$('resultImage').src=r.img;$('resultTitle').textContent=r.title;$('resultSummary').textContent=r.summary;$('scoreValue').textContent=`${total}%`;$('resultNumber').textContent=`REPORT 0${idx+1}`;const hot=chartValues.map((v,i)=>v>=80?wordFor(i,v):'').filter(Boolean);$('featureBurst').innerHTML=hot.slice(0,2).map(x=>`<span>${x}</span>`).join('');fillReport(total,idx);show('resultScreen');requestAnimationFrame(()=>drawChart(chartValues))}
function fillReport(total,idx){const maxIndex=chartValues.indexOf(Math.max(...chartValues));$('reportText').textContent=`本轮最明显的特征是“${wordFor(maxIndex,chartValues[maxIndex])}”。你的懂刚程度达到 ${total}%，目前属于“${results[idx].title}”。${comments[maxIndex][total>60?1:0]}`;$('quoteText').textContent=quotes[(maxIndex+idx)%quotes.length];const selected=questions.map((q,i)=>({q,i,a:answers[i]})).filter(x=>x.a>=2).slice(0,4);$('evidenceList').innerHTML=selected.length?selected.map(x=>`<div class="evidence-item"><b>第 ${x.i+1} 题</b>${x.q.opts[x.a]}</div>`).join(''):'<div class="evidence-item"><b>目前暂无</b>你这次的选择还没有留下明显的刚杂证据。</div>';$('dimensionList').innerHTML=dims.map((d,i)=>`<article class="dimension-card"><header><span>${d}</span><strong>${chartValues[i]}%</strong></header><p>${comments[i][chartValues[i]>60?1:0]}</p></article>`).join('');$('survivalStat').textContent=`${Math.max(0,100-chartValues[5])}%`;$('headphoneStat').textContent=chartValues[1]>60?'正在消失':'相对稳定';$('installmentStat').textContent=chartValues[4]>60?'1 天':chartValues[4]>35?'偶尔':'按时';$('siteStat').textContent=chartValues[5]>70?'已战略撤离':chartValues[5]>35?'看情况':'坚守中';const next=idx<5?results[idx+1].title:'没有更高等级了';const base=[0,15,30,50,70,85][idx],end=[15,30,50,70,85,100][idx];$('nextRankText').textContent=idx<5?`距离“${next}”还差 ${Math.max(0,end-total)} 分`:'你已经抵达刚杂浓度上限';$('rankProgress').style.width=`${Math.min(100,Math.max(5,((total-base)/(end-base))*100))}%`}
function drawChart(values){const c=$('radarCanvas'),ctx=c.getContext('2d'),w=c.width,h=c.height,cx=w/2,cy=h/2+8,R=Math.min(w,h)*.34;ctx.clearRect(0,0,w,h);const angles=values.map((_,i)=>-Math.PI/2+i*Math.PI*2/6);ctx.strokeStyle='rgba(255,255,255,.18)';ctx.lineWidth=1;for(let ring=1;ring<=4;ring++){ctx.beginPath();angles.forEach((a,i)=>{const r=R*ring/4,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.stroke()}angles.forEach(a=>{ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);ctx.stroke()});let progress=0;const animate=()=>{progress=Math.min(1,progress+.035);ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.18)';for(let ring=1;ring<=4;ring++){ctx.beginPath();angles.forEach((a,i)=>{const r=R*ring/4,x=cx+Math.cos(a)*r,y=cy+Math.sin(a)*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.stroke()}angles.forEach(a=>{ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*R,cy+Math.sin(a)*R);ctx.stroke()});ctx.beginPath();values.forEach((v,i)=>{const r=R*(v/100)*progress,x=cx+Math.cos(angles[i])*r,y=cy+Math.sin(angles[i])*r;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle='rgba(230,255,67,.22)';ctx.fill();ctx.strokeStyle='#e6ff43';ctx.lineWidth=3;ctx.stroke();values.forEach((v,i)=>{const r=R*(v/100)*progress;ctx.beginPath();ctx.arc(cx+Math.cos(angles[i])*r,cy+Math.sin(angles[i])*r,5,0,Math.PI*2);ctx.fillStyle='#ff7043';ctx.fill()});if(progress<1)requestAnimationFrame(animate);else labels(angles,R)};animate()}
function labels(angles,R){const box=$('axisLabels');box.innerHTML='';const rect=box.getBoundingClientRect();angles.forEach((a,i)=>{const el=document.createElement('div');el.className='axis-label';el.style.left=`${50+Math.cos(a)*43}%`;el.style.top=`${50+Math.sin(a)*43}%`;el.innerHTML=`${dims[i]}<b>${chartValues[i]}% · ${wordFor(i,chartValues[i])}</b>`;box.appendChild(el)})}
function saveImage(){const img=new Image();img.onload=()=>{const c=document.createElement('canvas'),ctx=c.getContext('2d');c.width=1200;c.height=1650;ctx.fillStyle='#171717';ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle='#e6ff43';ctx.font='900 72px sans-serif';ctx.fillText('刚学家',70,100);ctx.fillStyle='#fff';ctx.font='32px sans-serif';ctx.fillText('测测你的懂刚程度 / RESULT REPORT',72,150);ctx.drawImage(img,70,190,1060,620);ctx.fillStyle='#e6ff43';ctx.font='900 70px sans-serif';ctx.fillText($('scoreValue').textContent,72,900);ctx.fillStyle='#fff';ctx.font='900 42px sans-serif';ctx.fillText($('resultTitle').textContent,72,970);ctx.font='25px sans-serif';wrapText(ctx,$('resultSummary').textContent,72,1025,1050,42);const radar=$('radarCanvas');ctx.drawImage(radar,330,1110,540,435);ctx.fillStyle='#f4d35e';ctx.font='bold 21px sans-serif';chartValues.forEach((v,i)=>ctx.fillText(`${dims[i]}  ${v}%  ${wordFor(i,v)}`,72,1140+i*48));const hot=chartValues.map((v,i)=>v>=80?wordFor(i,v):'').filter(Boolean);if(hot.length){ctx.fillStyle='#f4d35e';ctx.font='900 36px sans-serif';ctx.fillText(hot.join(' · '),72,1588)}const a=document.createElement('a');a.download='gang-test-result.png';a.href=c.toDataURL('image/png');a.click();toast('结果图已保存，记得发给你的固排和室友');};img.src=$('resultImage').src}
function toast(message){let t=document.querySelector('.save-toast');if(!t){t=document.createElement('div');t.className='save-toast';document.body.appendChild(t)}t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function wrapText(ctx,text,x,y,maxWidth,lineHeight){let line='';for(const ch of text){if(ctx.measureText(line+ch).width>maxWidth){ctx.fillText(line,x,y);line=ch;y+=lineHeight}else line+=ch}ctx.fillText(line,x,y)}
$('startBtn').onclick=start;$('nextBtn').onclick=()=>{if(current<9){current++;renderQuestion()}else result()};$('backBtn').onclick=()=>{if(current>0){current--;renderQuestion()}};$('retryBtn').onclick=start;$('saveBtn').onclick=saveImage;
